# Generated by Django 6.1.1 on 2026-09-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('citation', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('requirement', models.TextField()),
                ('severity', models.CharField(choices=[('MAJOR', 'Major - legal violation'), ('MINOR', 'Minor - formatting defect'), ('INFO', 'Informational - not a Legal Metrology rule')], max_length=8)),
                ('kind', models.CharField(choices=[('PRESENCE', 'Mandatory declaration must be present'), ('FORMAT', 'Declaration present but must be written correctly'), ('INFO', 'Detected and displayed, no compliance claim')], max_length=10)),
                ('field', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False, help_text='Ticked once a team member has confirmed this citation against the Gazette text.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('verdict', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-compliant'), ('EXEMPT', 'Out of scope'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('product_label', models.CharField(blank=True, max_length=160)),
                ('is_imported', models.BooleanField(default=False)),
                ('exempt_reason', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Seeded example that replays without a network call.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardPackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=120)),
                ('keywords', models.CharField(help_text='Comma-separated words matched against the extracted common name.', max_length=240)),
                ('unit', models.CharField(default='g', max_length=4)),
                ('sizes', models.TextField(help_text='Comma-separated allowed sizes in the base unit.')),
                ('multiples_above', models.FloatField(blank=True, help_text='Above this value any multiple of `multiple_step` is allowed.', null=True)),
                ('multiple_step', models.FloatField(blank=True, null=True)),
                ('unrestricted_below', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['commodity'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(default=dict)),
                ('merged_fields', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='compliance.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('panel', models.CharField(choices=[('DECLARATION', 'Declaration panel'), ('FRONT', 'Front panel')], default='DECLARATION', max_length=12)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='compliance.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('SKIP', 'Not applicable'), ('INFO', 'Info')], max_length=6)),
                ('severity', models.CharField(max_length=8)),
                ('observed', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.rule')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='compliance.scan')),
            ],
            options={
                'ordering': ['rule__order', 'rule__code'],
            },
        ),
    ]
