# Generated by Django 6.1.1 on 2026-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='verdict',
            field=models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-compliant'), ('INCOMPLETE', 'Incomplete - a declaration sits on an unseen panel'), ('EXEMPT', 'Out of scope'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('SKIP', 'Not applicable'), ('RECHECK', 'Declared on another panel - not checked'), ('INFO', 'Info')], max_length=8),
        ),
    ]